// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/waapp/v1/common.proto

/* eslint-disable */

export const protobufPackage = "byte.v.forge.waapp.v1";

export enum WaErrorCode {
  WA_ERROR_CODE_UNSPECIFIED = "WA_ERROR_CODE_UNSPECIFIED",
  WA_ERROR_CODE_VALIDATION_FAILED = "WA_ERROR_CODE_VALIDATION_FAILED",
  WA_ERROR_CODE_WA_ACCOUNT_NOT_FOUND = "WA_ERROR_CODE_WA_ACCOUNT_NOT_FOUND",
  WA_ERROR_CODE_PROFILE_NOT_FOUND = "WA_ERROR_CODE_PROFILE_NOT_FOUND",
  WA_ERROR_CODE_PROTOCOL_PROFILE_NOT_FOUND = "WA_ERROR_CODE_PROTOCOL_PROFILE_NOT_FOUND",
  WA_ERROR_CODE_REGISTRATION_NOT_FOUND = "WA_ERROR_CODE_REGISTRATION_NOT_FOUND",
  WA_ERROR_CODE_MESSAGE_SESSION_NOT_FOUND = "WA_ERROR_CODE_MESSAGE_SESSION_NOT_FOUND",
  WA_ERROR_CODE_MESSAGE_NOT_FOUND = "WA_ERROR_CODE_MESSAGE_NOT_FOUND",
  WA_ERROR_CODE_ROUTE_UNAVAILABLE = "WA_ERROR_CODE_ROUTE_UNAVAILABLE",
  WA_ERROR_CODE_RATE_LIMITED = "WA_ERROR_CODE_RATE_LIMITED",
  WA_ERROR_CODE_REJECTED = "WA_ERROR_CODE_REJECTED",
  WA_ERROR_CODE_EXPIRED = "WA_ERROR_CODE_EXPIRED",
  WA_ERROR_CODE_CONFLICT = "WA_ERROR_CODE_CONFLICT",
  WA_ERROR_CODE_DECRYPTION_FAILED = "WA_ERROR_CODE_DECRYPTION_FAILED",
  WA_ERROR_CODE_UNSUPPORTED_OPERATION = "WA_ERROR_CODE_UNSUPPORTED_OPERATION",
  WA_ERROR_CODE_INTERNAL = "WA_ERROR_CODE_INTERNAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface RequestContext {
  request_id: string;
  workspace_id: string;
  actor_id: string;
  correlation_id: string;
  trace_id: string;
}

export interface WaError {
  code: WaErrorCode;
  message: string;
  retryable: boolean;
}

export interface PhoneTarget {
  e164_number: string;
  country_calling_code: string;
  national_number: string;
  country_iso2: string;
}

export interface SensitiveText {
  /** Sensitive value returned only when the caller explicitly requests it. */
  value: string;
  redacted_value: string;
  secret_ref: string;
}

export interface AuditStamp {
  created_at: string | undefined;
  updated_at: string | undefined;
}
