// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/waapp/v1/discovery.proto

/* eslint-disable */
import type { AuditStamp, RequestContext, WaError } from "./common";

export const protobufPackage = "byte.v.forge.waapp.v1";

export enum ProtocolProfileStatus {
  PROTOCOL_PROFILE_STATUS_UNSPECIFIED = "PROTOCOL_PROFILE_STATUS_UNSPECIFIED",
  PROTOCOL_PROFILE_STATUS_DRAFT = "PROTOCOL_PROFILE_STATUS_DRAFT",
  PROTOCOL_PROFILE_STATUS_ACTIVE = "PROTOCOL_PROFILE_STATUS_ACTIVE",
  PROTOCOL_PROFILE_STATUS_DEPRECATED = "PROTOCOL_PROFILE_STATUS_DEPRECATED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProtocolCapability {
  PROTOCOL_CAPABILITY_UNSPECIFIED = "PROTOCOL_CAPABILITY_UNSPECIFIED",
  PROTOCOL_CAPABILITY_ACCOUNT_PROBE = "PROTOCOL_CAPABILITY_ACCOUNT_PROBE",
  PROTOCOL_CAPABILITY_CODE_REQUEST = "PROTOCOL_CAPABILITY_CODE_REQUEST",
  PROTOCOL_CAPABILITY_CODE_SUBMIT = "PROTOCOL_CAPABILITY_CODE_SUBMIT",
  PROTOCOL_CAPABILITY_MESSAGE_SESSION = "PROTOCOL_CAPABILITY_MESSAGE_SESSION",
  PROTOCOL_CAPABILITY_MESSAGE_ACK = "PROTOCOL_CAPABILITY_MESSAGE_ACK",
  PROTOCOL_CAPABILITY_ENCRYPTED_MESSAGE_DECRYPTION = "PROTOCOL_CAPABILITY_ENCRYPTED_MESSAGE_DECRYPTION",
  PROTOCOL_CAPABILITY_CANDIDATE_EXTRACTION = "PROTOCOL_CAPABILITY_CANDIDATE_EXTRACTION",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum RegistrationFlowKind {
  REGISTRATION_FLOW_KIND_UNSPECIFIED = "REGISTRATION_FLOW_KIND_UNSPECIFIED",
  REGISTRATION_FLOW_KIND_EXISTING_ACCOUNT = "REGISTRATION_FLOW_KIND_EXISTING_ACCOUNT",
  REGISTRATION_FLOW_KIND_NEW_ACCOUNT = "REGISTRATION_FLOW_KIND_NEW_ACCOUNT",
  REGISTRATION_FLOW_KIND_RECOVERY = "REGISTRATION_FLOW_KIND_RECOVERY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum MessageTransportKind {
  MESSAGE_TRANSPORT_KIND_UNSPECIFIED = "MESSAGE_TRANSPORT_KIND_UNSPECIFIED",
  MESSAGE_TRANSPORT_KIND_LONG_CONNECTION = "MESSAGE_TRANSPORT_KIND_LONG_CONNECTION",
  MESSAGE_TRANSPORT_KIND_POLLING = "MESSAGE_TRANSPORT_KIND_POLLING",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface AppArtifact {
  artifact_id: string;
  label: string;
  version_label: string;
  sha256: string;
  observed_at: string | undefined;
}

export interface ProtocolProfile {
  protocol_profile_id: string;
  app_artifact_id: string;
  display_name: string;
  app_version: string;
  status: ProtocolProfileStatus;
  capabilities: ProtocolCapability[];
  registration_flows: RegistrationFlowKind[];
  message_transports: MessageTransportKind[];
  discovered_at: string | undefined;
  audit: AuditStamp | undefined;
}

export interface RegisterAppArtifactRequest {
  context: RequestContext | undefined;
  label: string;
  version_label: string;
  sha256: string;
}

export interface RegisterAppArtifactResponse {
  artifact: AppArtifact | undefined;
  error: WaError | undefined;
}

export interface RecordProtocolProfileRequest {
  context: RequestContext | undefined;
  app_artifact_id: string;
  display_name: string;
  app_version: string;
  capabilities: ProtocolCapability[];
  registration_flows: RegistrationFlowKind[];
  message_transports: MessageTransportKind[];
}

export interface RecordProtocolProfileResponse {
  protocol_profile: ProtocolProfile | undefined;
  error: WaError | undefined;
}

export interface GetProtocolProfileRequest {
  context: RequestContext | undefined;
  protocol_profile_id: string;
}

export interface GetProtocolProfileResponse {
  protocol_profile: ProtocolProfile | undefined;
  error: WaError | undefined;
}
