// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/waapp/v1/extraction.proto

/* eslint-disable */
import type { RequestContext, SensitiveText, WaError } from "./common";

export const protobufPackage = "byte.v.forge.waapp.v1";

export enum DecryptionStatus {
  DECRYPTION_STATUS_UNSPECIFIED = "DECRYPTION_STATUS_UNSPECIFIED",
  DECRYPTION_STATUS_PENDING = "DECRYPTION_STATUS_PENDING",
  DECRYPTION_STATUS_DECRYPTED = "DECRYPTION_STATUS_DECRYPTED",
  DECRYPTION_STATUS_FAILED = "DECRYPTION_STATUS_FAILED",
  DECRYPTION_STATUS_UNSUPPORTED = "DECRYPTION_STATUS_UNSUPPORTED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SessionCommitPolicy {
  SESSION_COMMIT_POLICY_UNSPECIFIED = "SESSION_COMMIT_POLICY_UNSPECIFIED",
  SESSION_COMMIT_POLICY_TRANSIENT = "SESSION_COMMIT_POLICY_TRANSIENT",
  SESSION_COMMIT_POLICY_COMMIT_LEARNED_STATE = "SESSION_COMMIT_POLICY_COMMIT_LEARNED_STATE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CandidateKind {
  CANDIDATE_KIND_UNSPECIFIED = "CANDIDATE_KIND_UNSPECIFIED",
  CANDIDATE_KIND_OTP = "CANDIDATE_KIND_OTP",
  CANDIDATE_KIND_FLAG = "CANDIDATE_KIND_FLAG",
  CANDIDATE_KIND_CODE = "CANDIDATE_KIND_CODE",
  CANDIDATE_KIND_TEXT = "CANDIDATE_KIND_TEXT",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface DecryptedMessage {
  decrypted_message_id: string;
  message_id: string;
  status: DecryptionStatus;
  plaintext_ref: string;
  /** Sensitive. Populated only when explicitly requested for an authorized caller. */
  plaintext_text: SensitiveText | undefined;
  decrypted_at: string | undefined;
  last_error: WaError | undefined;
}

export interface ExtractedCandidate {
  candidate_id: string;
  message_id: string;
  decrypted_message_id: string;
  kind: CandidateKind;
  text: SensitiveText | undefined;
  confidence: number;
  extracted_at: string | undefined;
}

export interface DecryptMessageRequest {
  context: RequestContext | undefined;
  message_id: string;
  session_commit_policy: SessionCommitPolicy;
  include_sensitive_plaintext: boolean;
}

export interface DecryptMessageResponse {
  decrypted_message: DecryptedMessage | undefined;
  error: WaError | undefined;
}

export interface ExtractCandidatesRequest {
  context: RequestContext | undefined;
  message_id: string;
  decrypted_message_id: string;
  candidate_kinds: CandidateKind[];
  include_sensitive_values: boolean;
}

export interface ExtractCandidatesResponse {
  candidates: ExtractedCandidate[];
  error: WaError | undefined;
}
