// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/waapp/v1/messaging.proto

/* eslint-disable */
import type { RequestContext, WaError } from "./common";

export const protobufPackage = "byte.v.forge.waapp.v1";

export enum MessageSessionStatus {
  MESSAGE_SESSION_STATUS_UNSPECIFIED = "MESSAGE_SESSION_STATUS_UNSPECIFIED",
  MESSAGE_SESSION_STATUS_OPENING = "MESSAGE_SESSION_STATUS_OPENING",
  MESSAGE_SESSION_STATUS_OPEN = "MESSAGE_SESSION_STATUS_OPEN",
  MESSAGE_SESSION_STATUS_DRAINING = "MESSAGE_SESSION_STATUS_DRAINING",
  MESSAGE_SESSION_STATUS_CLOSED = "MESSAGE_SESSION_STATUS_CLOSED",
  MESSAGE_SESSION_STATUS_FAILED = "MESSAGE_SESSION_STATUS_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum InboundMessageKind {
  INBOUND_MESSAGE_KIND_UNSPECIFIED = "INBOUND_MESSAGE_KIND_UNSPECIFIED",
  INBOUND_MESSAGE_KIND_MESSAGE = "INBOUND_MESSAGE_KIND_MESSAGE",
  INBOUND_MESSAGE_KIND_NOTIFICATION = "INBOUND_MESSAGE_KIND_NOTIFICATION",
  INBOUND_MESSAGE_KIND_RECEIPT = "INBOUND_MESSAGE_KIND_RECEIPT",
  INBOUND_MESSAGE_KIND_SYSTEM = "INBOUND_MESSAGE_KIND_SYSTEM",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum MessageEncryptionState {
  MESSAGE_ENCRYPTION_STATE_UNSPECIFIED = "MESSAGE_ENCRYPTION_STATE_UNSPECIFIED",
  MESSAGE_ENCRYPTION_STATE_PLAINTEXT = "MESSAGE_ENCRYPTION_STATE_PLAINTEXT",
  MESSAGE_ENCRYPTION_STATE_ENCRYPTED = "MESSAGE_ENCRYPTION_STATE_ENCRYPTED",
  MESSAGE_ENCRYPTION_STATE_DECRYPTED = "MESSAGE_ENCRYPTION_STATE_DECRYPTED",
  MESSAGE_ENCRYPTION_STATE_DECRYPTION_FAILED = "MESSAGE_ENCRYPTION_STATE_DECRYPTION_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum MessageAckStatus {
  MESSAGE_ACK_STATUS_UNSPECIFIED = "MESSAGE_ACK_STATUS_UNSPECIFIED",
  MESSAGE_ACK_STATUS_NOT_REQUIRED = "MESSAGE_ACK_STATUS_NOT_REQUIRED",
  MESSAGE_ACK_STATUS_PENDING = "MESSAGE_ACK_STATUS_PENDING",
  MESSAGE_ACK_STATUS_ACKED = "MESSAGE_ACK_STATUS_ACKED",
  MESSAGE_ACK_STATUS_FAILED = "MESSAGE_ACK_STATUS_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum LongConnectionStatus {
  LONG_CONNECTION_STATUS_UNSPECIFIED = "LONG_CONNECTION_STATUS_UNSPECIFIED",
  LONG_CONNECTION_STATUS_STARTING = "LONG_CONNECTION_STATUS_STARTING",
  LONG_CONNECTION_STATUS_CONNECTED = "LONG_CONNECTION_STATUS_CONNECTED",
  LONG_CONNECTION_STATUS_HEARTBEAT_WAITING = "LONG_CONNECTION_STATUS_HEARTBEAT_WAITING",
  LONG_CONNECTION_STATUS_RECONNECTING = "LONG_CONNECTION_STATUS_RECONNECTING",
  LONG_CONNECTION_STATUS_FAILED = "LONG_CONNECTION_STATUS_FAILED",
  LONG_CONNECTION_STATUS_STOPPED = "LONG_CONNECTION_STATUS_STOPPED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface MessageSession {
  message_session_id: string;
  wa_account_id: string;
  client_profile_id: string;
  registered_identity_id: string;
  protocol_profile_id: string;
  status: MessageSessionStatus;
  opened_at: string | undefined;
  last_seen_at: string | undefined;
  closed_at: string | undefined;
  last_error: WaError | undefined;
}

export interface InboundMessage {
  message_id: string;
  message_session_id: string;
  kind: InboundMessageKind;
  encryption_state: MessageEncryptionState;
  ack_status: MessageAckStatus;
  sender_ref: string;
  payload_ref: string;
  received_at: string | undefined;
  last_error: WaError | undefined;
}

export interface LongConnectionState {
  workspace_id: string;
  login_state_id: string;
  wa_account_id: string;
  client_profile_id: string;
  registered_identity_id: string;
  message_session_id: string;
  status: LongConnectionStatus;
  heartbeat_supported: boolean;
  started_at: string | undefined;
  last_connected_at: string | undefined;
  last_heartbeat_at: string | undefined;
  last_message_at: string | undefined;
  reconnect_count: number;
  last_error: WaError | undefined;
}

export interface OpenMessageSessionRequest {
  context: RequestContext | undefined;
  wa_account_id: string;
  client_profile_id: string;
  registered_identity_id: string;
  protocol_profile_id: string;
}

export interface OpenMessageSessionResponse {
  session: MessageSession | undefined;
  error: WaError | undefined;
}

export interface GetMessageSessionRequest {
  context: RequestContext | undefined;
  message_session_id: string;
}

export interface GetMessageSessionResponse {
  session: MessageSession | undefined;
  error: WaError | undefined;
}

export interface ReceiveMessageBatchRequest {
  context: RequestContext | undefined;
  message_session_id: string;
  max_messages: number;
  wait_timeout: string | undefined;
}

export interface ReceiveMessageBatchResponse {
  messages: InboundMessage[];
  session: MessageSession | undefined;
  error: WaError | undefined;
}

export interface GetLongConnectionStatusRequest {
  context: RequestContext | undefined;
  login_state_id: string;
  wa_account_id: string;
  client_profile_id: string;
  registered_identity_id: string;
}

export interface GetLongConnectionStatusResponse {
  connections: LongConnectionState[];
  error: WaError | undefined;
}

export interface AcknowledgeMessageRequest {
  context: RequestContext | undefined;
  message_session_id: string;
  message_id: string;
}

export interface AcknowledgeMessageResponse {
  message: InboundMessage | undefined;
  error: WaError | undefined;
}

export interface CloseMessageSessionRequest {
  context: RequestContext | undefined;
  message_session_id: string;
  reason: string;
}

export interface CloseMessageSessionResponse {
  session: MessageSession | undefined;
  error: WaError | undefined;
}
