// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/waapp/v1/registration.proto

/* eslint-disable */
import type { AuditStamp, RequestContext, WaError } from "./common";

export const protobufPackage = "byte.v.forge.waapp.v1";

export enum AccountProbeStatus {
  ACCOUNT_PROBE_STATUS_UNSPECIFIED = "ACCOUNT_PROBE_STATUS_UNSPECIFIED",
  ACCOUNT_PROBE_STATUS_UNKNOWN = "ACCOUNT_PROBE_STATUS_UNKNOWN",
  ACCOUNT_PROBE_STATUS_REACHABLE = "ACCOUNT_PROBE_STATUS_REACHABLE",
  ACCOUNT_PROBE_STATUS_UNREACHABLE = "ACCOUNT_PROBE_STATUS_UNREACHABLE",
  ACCOUNT_PROBE_STATUS_REJECTED = "ACCOUNT_PROBE_STATUS_REJECTED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum VerificationDeliveryMethod {
  VERIFICATION_DELIVERY_METHOD_UNSPECIFIED = "VERIFICATION_DELIVERY_METHOD_UNSPECIFIED",
  VERIFICATION_DELIVERY_METHOD_SMS = "VERIFICATION_DELIVERY_METHOD_SMS",
  VERIFICATION_DELIVERY_METHOD_VOICE = "VERIFICATION_DELIVERY_METHOD_VOICE",
  VERIFICATION_DELIVERY_METHOD_IN_APP_MESSAGE = "VERIFICATION_DELIVERY_METHOD_IN_APP_MESSAGE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum VerificationRequestStatus {
  VERIFICATION_REQUEST_STATUS_UNSPECIFIED = "VERIFICATION_REQUEST_STATUS_UNSPECIFIED",
  VERIFICATION_REQUEST_STATUS_REQUESTED = "VERIFICATION_REQUEST_STATUS_REQUESTED",
  VERIFICATION_REQUEST_STATUS_SENT = "VERIFICATION_REQUEST_STATUS_SENT",
  VERIFICATION_REQUEST_STATUS_WAITING = "VERIFICATION_REQUEST_STATUS_WAITING",
  VERIFICATION_REQUEST_STATUS_REJECTED = "VERIFICATION_REQUEST_STATUS_REJECTED",
  VERIFICATION_REQUEST_STATUS_EXPIRED = "VERIFICATION_REQUEST_STATUS_EXPIRED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum RegistrationStatus {
  REGISTRATION_STATUS_UNSPECIFIED = "REGISTRATION_STATUS_UNSPECIFIED",
  REGISTRATION_STATUS_PENDING_CODE = "REGISTRATION_STATUS_PENDING_CODE",
  REGISTRATION_STATUS_SUBMITTED = "REGISTRATION_STATUS_SUBMITTED",
  REGISTRATION_STATUS_REGISTERED = "REGISTRATION_STATUS_REGISTERED",
  REGISTRATION_STATUS_REJECTED = "REGISTRATION_STATUS_REJECTED",
  REGISTRATION_STATUS_EXPIRED = "REGISTRATION_STATUS_EXPIRED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum LoginStateStatus {
  LOGIN_STATE_STATUS_UNSPECIFIED = "LOGIN_STATE_STATUS_UNSPECIFIED",
  LOGIN_STATE_STATUS_ACTIVE = "LOGIN_STATE_STATUS_ACTIVE",
  LOGIN_STATE_STATUS_INVALID = "LOGIN_STATE_STATUS_INVALID",
  LOGIN_STATE_STATUS_REVOKED = "LOGIN_STATE_STATUS_REVOKED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum LoginStateCheckStatus {
  LOGIN_STATE_CHECK_STATUS_UNSPECIFIED = "LOGIN_STATE_CHECK_STATUS_UNSPECIFIED",
  LOGIN_STATE_CHECK_STATUS_ACTIVE = "LOGIN_STATE_CHECK_STATUS_ACTIVE",
  LOGIN_STATE_CHECK_STATUS_INVALID = "LOGIN_STATE_CHECK_STATUS_INVALID",
  LOGIN_STATE_CHECK_STATUS_UNREACHABLE = "LOGIN_STATE_CHECK_STATUS_UNREACHABLE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface AccountProbe {
  account_probe_id: string;
  wa_account_id: string;
  client_profile_id: string;
  status: AccountProbeStatus;
  supported_methods: VerificationDeliveryMethod[];
  probed_at: string | undefined;
  last_error: WaError | undefined;
}

export interface VerificationCodeRequestRecord {
  verification_request_id: string;
  wa_account_id: string;
  client_profile_id: string;
  delivery_method: VerificationDeliveryMethod;
  status: VerificationRequestStatus;
  expected_code_length: number;
  requested_at: string | undefined;
  expires_at: string | undefined;
  last_error: WaError | undefined;
}

export interface RegisteredIdentity {
  registered_identity_id: string;
  wa_account_id: string;
  client_profile_id: string;
  service_account_id: string;
  service_login_id: string;
  registered_at: string | undefined;
}

export interface RegistrationRecord {
  registration_id: string;
  verification_request_id: string;
  wa_account_id: string;
  client_profile_id: string;
  status: RegistrationStatus;
  identity: RegisteredIdentity | undefined;
  submitted_at: string | undefined;
  completed_at: string | undefined;
  last_error: WaError | undefined;
}

export interface LoginState {
  login_state_id: string;
  registration_id: string;
  wa_account_id: string;
  client_profile_id: string;
  registered_identity_id: string;
  service_account_id: string;
  service_login_id: string;
  status: LoginStateStatus;
  registered_at: string | undefined;
  last_verified_at: string | undefined;
  audit: AuditStamp | undefined;
  last_error: WaError | undefined;
}

export interface LoginStateCheck {
  login_state_check_id: string;
  login_state_id: string;
  wa_account_id: string;
  client_profile_id: string;
  registered_identity_id: string;
  status: LoginStateCheckStatus;
  checked_at: string | undefined;
  error: WaError | undefined;
}

export interface ProbeAccountRequest {
  context: RequestContext | undefined;
  wa_account_id: string;
  client_profile_id: string;
  protocol_profile_id: string;
}

export interface ProbeAccountResponse {
  probe: AccountProbe | undefined;
  error: WaError | undefined;
}

export interface RequestVerificationCodeRequest {
  context: RequestContext | undefined;
  wa_account_id: string;
  client_profile_id: string;
  protocol_profile_id: string;
  delivery_method: VerificationDeliveryMethod;
}

export interface RequestVerificationCodeResponse {
  verification_request: VerificationCodeRequestRecord | undefined;
  error: WaError | undefined;
}

export interface SubmitVerificationCodeRequest {
  context: RequestContext | undefined;
  verification_request_id: string;
  /** Sensitive. Do not log or persist as plaintext outside the authorized registration operation. */
  code?: string | undefined;
  code_secret_ref?: string | undefined;
}

export interface SubmitVerificationCodeResponse {
  registration: RegistrationRecord | undefined;
  error: WaError | undefined;
  login_state: LoginState | undefined;
}

export interface GetRegistrationRequest {
  context: RequestContext | undefined;
  registration_id: string;
}

export interface GetRegistrationResponse {
  registration: RegistrationRecord | undefined;
  error: WaError | undefined;
}

export interface GetLoginStateRequest {
  context: RequestContext | undefined;
  login_state_id: string;
}

export interface GetLoginStateResponse {
  login_state: LoginState | undefined;
  error: WaError | undefined;
}

export interface GetActiveLoginStateRequest {
  context: RequestContext | undefined;
  wa_account_id: string;
  client_profile_id: string;
}

export interface GetActiveLoginStateResponse {
  login_state: LoginState | undefined;
  error: WaError | undefined;
}

export interface CheckLoginStateRequest {
  context: RequestContext | undefined;
  login_state_id: string;
  wa_account_id: string;
  client_profile_id: string;
  registered_identity_id: string;
  remote_timeout: string | undefined;
}

export interface CheckLoginStateResponse {
  login_state: LoginState | undefined;
  check: LoginStateCheck | undefined;
  error: WaError | undefined;
}
