// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/waapp/v1/tooling.proto

/* eslint-disable */
import type { PhoneTarget, RequestContext, SensitiveText, WaError } from "./common";

export const protobufPackage = "byte.v.forge.waapp.v1";

export enum RegistrationRequestKind {
  REGISTRATION_REQUEST_KIND_UNSPECIFIED = "REGISTRATION_REQUEST_KIND_UNSPECIFIED",
  REGISTRATION_REQUEST_KIND_EXIST = "REGISTRATION_REQUEST_KIND_EXIST",
  REGISTRATION_REQUEST_KIND_CODE = "REGISTRATION_REQUEST_KIND_CODE",
  REGISTRATION_REQUEST_KIND_REGISTER = "REGISTRATION_REQUEST_KIND_REGISTER",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface PhoneFingerprintProfile {
  schema: string;
  phone: PhoneTarget | undefined;
  phone_sha256: string;
  user_agent: string;
  base_params: { [key: string]: string };
  raw_params: { [key: string]: string };
  device_map_params: { [key: string]: string };
  profile_sha256: string;
}

export interface PhoneFingerprintProfile_BaseParamsEntry {
  key: string;
  value: string;
}

export interface PhoneFingerprintProfile_RawParamsEntry {
  key: string;
  value: string;
}

export interface PhoneFingerprintProfile_DeviceMapParamsEntry {
  key: string;
  value: string;
}

export interface RegistrationRequestParam {
  key: string;
  value: SensitiveText | undefined;
  raw_percent_encoded: boolean;
}

export interface WamsysScalarField {
  field_name: string;
  value: string;
}

export interface WamsysMapParam {
  key: string;
  value: Uint8Array;
}

export interface WamsysByteField {
  field_name: string;
  value: Uint8Array;
}

export interface WamsysCapture {
  scalar_fields: WamsysScalarField[];
  map_params: WamsysMapParam[];
  byte_fields: WamsysByteField[];
}

export interface GeneratePhoneFingerprintProfileRequest {
  context: RequestContext | undefined;
  phone: PhoneTarget | undefined;
  app_version: string;
}

export interface GeneratePhoneFingerprintProfileResponse {
  profile: PhoneFingerprintProfile | undefined;
  error: WaError | undefined;
}

export interface ImportWamsysCaptureRequest {
  context: RequestContext | undefined;
  json_text: string;
}

export interface ImportWamsysCaptureResponse {
  capture: WamsysCapture | undefined;
  error: WaError | undefined;
}

export interface BuildRegistrationRequestRequest {
  context: RequestContext | undefined;
  kind: RegistrationRequestKind;
  phone: PhoneTarget | undefined;
  client_profile_id: string;
  method: string;
  language: string;
  locale: string;
  verification_code: string;
  wamsys_capture: WamsysCapture | undefined;
  apply_wamsys_scalars: boolean;
  include_wamsys_map: boolean;
  include_wamsys_id_backup: boolean;
  extra_params: RegistrationRequestParam[];
  include_sensitive_values: boolean;
  encrypt_request: boolean;
}

export interface BuildRegistrationRequestResponse {
  params: RegistrationRequestParam[];
  raw_param_keys: string[];
  plaintext: SensitiveText | undefined;
  body: SensitiveText | undefined;
  enc_sha256: string;
  enc_length: number;
  headers: { [key: string]: string };
  user_agent: string;
  error: WaError | undefined;
}

export interface BuildRegistrationRequestResponse_HeadersEntry {
  key: string;
  value: string;
}

export interface EncryptWASafeEnvelopeRequest {
  context: RequestContext | undefined;
  plaintext: SensitiveText | undefined;
  server_public_key_hex: string;
  include_sensitive_values: boolean;
}

export interface EncryptWASafeEnvelopeResponse {
  enc: SensitiveText | undefined;
  enc_sha256: string;
  enc_length: number;
  error: WaError | undefined;
}

export interface DeriveRegistrationTokenRequest {
  context: RequestContext | undefined;
  apk: Uint8Array;
  phone: PhoneTarget | undefined;
  package_name: string;
  include_sensitive_values: boolean;
}

export interface DeriveRegistrationTokenResponse {
  token: SensitiveText | undefined;
  error: WaError | undefined;
}

export interface DeriveAuthKeyRequest {
  context: RequestContext | undefined;
  keystore_xml: string;
  include_sensitive_values: boolean;
}

export interface DeriveAuthKeyResponse {
  authkey: SensitiveText | undefined;
  error: WaError | undefined;
}
